schema = 1
name = "Example Mod"
modid = "example"
description = """
Cool description for your project.
"""
version = "${version}"
mixins = "example.mixins.json"

[[entrypoints]]
id = "common"
specifier = "org.example.mod.ExampleMod"

[[entrypoints]]
id = "client"
specifier = "org.example.mod.client.ExampleModClient"

